spring:
    application:
        name: hello-spring

    datasource:
        driver-class-name: oracle.jdbc.OracleDriver
        url: jdbc:oracle:thin:@localhost:1521/xe
        username: juniel
        password: java1234